name: Monitornship

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run internship monitor
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        run: python main.py

      - name: Save job history
        run: |
          git config user.name "Monitornship Bot"
          git config user.email "actions@github.com"
          git add jobList.json
          git diff --cached --quiet || git commit -m "Update internship history"
          git push